

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "BusinessObject\App.config"
//     Connection String Name: "DefaultConnection"
//     Connection String:      "Data Source=hng3-sql2k19;Initial Catalog=2021HN0032_CyDenture;Integrated Security=False;Integrated Security=SSPI;MultipleActiveResultSets=True"
// ------------------------------------------------------------------------------------------------
